package settings

import (
	"fmt"
	"os"
)

var retiredYouTubeProducerEnvKeys = []string{
	"YOUTUBE_PRODUCER_FETCHER_ENGINE",
	"YOUTUBE_PRODUCER_REQUEST_INTERVAL_SECONDS",
	"YOUTUBE_PRODUCER_DISTRIBUTED_RATELIMIT_ENABLED",
	"YOUTUBE_PRODUCER_DISTRIBUTED_RATELIMIT_LIMIT",
	"YOUTUBE_PRODUCER_DISTRIBUTED_RATELIMIT_KEY_PREFIX",
	"YOUTUBE_PRODUCER_DISTRIBUTED_RATELIMIT_BUCKET_BASE",
	"YOUTUBE_PRODUCER_ACTIVE_ACTIVE_ENABLED",
	"YOUTUBE_PRODUCER_INSTANCE_ID",
	"YOUTUBE_PRODUCER_LEASE_NAMESPACE",
	"YOUTUBE_PRODUCER_GLOBAL_BUDGET_ENABLED",
	"YOUTUBE_PRODUCER_ACTIVE_ACTIVE_INSTANCE_COUNT",
	"YOUTUBE_PRODUCER_BUDGET_ACQUIRE_TIMEOUT_MS",
	"YOUTUBE_PRODUCER_BUDGET_YOUTUBE_SCRAPER_MAX_INFLIGHT",
	"YOUTUBE_PRODUCER_BUDGET_HOLODEX_LIVE_MAX_INFLIGHT",
	"YOUTUBE_PRODUCER_BUDGET_BROWSER_SNAPSHOT_MAX_INFLIGHT",
	"YOUTUBE_PRODUCER_BUDGET_BACKFILL_MAX_INFLIGHT",
	"YOUTUBE_PRODUCER_BUDGET_FALLBACK_MAX_INFLIGHT",
	"YOUTUBE_PRODUCER_BUDGET_CLEANUP_LIMIT",
	"YOUTUBE_PRODUCER_BUDGET_WINDOW_CHECK_ENABLED",
}

func rejectRetiredYouTubeProducerEnv() error {
	for _, key := range retiredYouTubeProducerEnvKeys {
		if _, found := os.LookupEnv(key); found {
			return fmt.Errorf("%s is retired; use YOUTUBE_REQUEST_INTERVAL_SECONDS and YOUTUBE_DISTRIBUTED_RATELIMIT_*", key)
		}
	}
	return nil
}
