apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: holo-postgres-external
  namespace: hololive
$patch: delete
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: iris-external
  namespace: hololive
$patch: delete
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: cliproxy-external
  namespace: hololive
$patch: delete
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: llm-server-external
  namespace: hololive
$patch: delete
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: game-bot-twentyq-external
  namespace: hololive
$patch: delete
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: game-bot-turtle-external
  namespace: hololive
$patch: delete
