// Code generated by scripts/architecture/generate-admin-docker-policy.mjs; DO NOT EDIT.
package docker

// PolicyHash는 앱과 전용 proxy가 공유하는 허용 정책의 SHA-256입니다.
const PolicyHash = "9e2e88cfd54c8836ff986e561fc542d874550fec5bab6d3b52cec6c8e7254d3a"

var containerActions = map[string]uint8{
	"admin-dashboard":              5,
	"admin-dashboard-ingress":      5,
	"admin-docker-proxy":           5,
	"deunhealth":                   5,
	"holo-postgres":                5,
	"hololive-alarm-worker":        7,
	"hololive-api":                 7,
	"hololive-youtube-collector-c": 7,
	"valkey-cache":                 5,
}
