INSERT INTO youtube_channel_profile_heads (
    channel_id,
    handle_set, handle, handle_effective_at,
    description_set, description, description_effective_at,
    description_empty_slots, description_empty_first_scheduled_for,
    description_empty_last_scheduled_for, description_empty_first_received_at,
    country_set, country, country_effective_at,
    country_empty_slots, country_empty_first_scheduled_for,
    country_empty_last_scheduled_for, country_empty_first_received_at,
    joined_date_set, joined_date, joined_date_effective_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
ON CONFLICT (channel_id) DO UPDATE SET
    handle_set = excluded.handle_set,
    handle = excluded.handle,
    handle_effective_at = excluded.handle_effective_at,
    description_set = excluded.description_set,
    description = excluded.description,
    description_effective_at = excluded.description_effective_at,
    description_empty_slots = excluded.description_empty_slots,
    description_empty_first_scheduled_for = excluded.description_empty_first_scheduled_for,
    description_empty_last_scheduled_for = excluded.description_empty_last_scheduled_for,
    description_empty_first_received_at = excluded.description_empty_first_received_at,
    country_set = excluded.country_set,
    country = excluded.country,
    country_effective_at = excluded.country_effective_at,
    country_empty_slots = excluded.country_empty_slots,
    country_empty_first_scheduled_for = excluded.country_empty_first_scheduled_for,
    country_empty_last_scheduled_for = excluded.country_empty_last_scheduled_for,
    country_empty_first_received_at = excluded.country_empty_first_received_at,
    joined_date_set = excluded.joined_date_set,
    joined_date = excluded.joined_date,
    joined_date_effective_at = excluded.joined_date_effective_at,
    updated_at = NOW()
WHERE (youtube_channel_profile_heads.handle_set, youtube_channel_profile_heads.handle,
       youtube_channel_profile_heads.handle_effective_at,
       youtube_channel_profile_heads.description_set, youtube_channel_profile_heads.description,
       youtube_channel_profile_heads.description_effective_at,
       youtube_channel_profile_heads.description_empty_slots,
       youtube_channel_profile_heads.description_empty_first_scheduled_for,
       youtube_channel_profile_heads.description_empty_last_scheduled_for,
       youtube_channel_profile_heads.description_empty_first_received_at,
       youtube_channel_profile_heads.country_set, youtube_channel_profile_heads.country,
       youtube_channel_profile_heads.country_effective_at,
       youtube_channel_profile_heads.country_empty_slots,
       youtube_channel_profile_heads.country_empty_first_scheduled_for,
       youtube_channel_profile_heads.country_empty_last_scheduled_for,
       youtube_channel_profile_heads.country_empty_first_received_at,
       youtube_channel_profile_heads.joined_date_set, youtube_channel_profile_heads.joined_date,
       youtube_channel_profile_heads.joined_date_effective_at)
IS DISTINCT FROM (excluded.handle_set, excluded.handle, excluded.handle_effective_at,
                  excluded.description_set, excluded.description, excluded.description_effective_at,
                  excluded.description_empty_slots, excluded.description_empty_first_scheduled_for,
                  excluded.description_empty_last_scheduled_for, excluded.description_empty_first_received_at,
                  excluded.country_set, excluded.country, excluded.country_effective_at,
                  excluded.country_empty_slots, excluded.country_empty_first_scheduled_for,
                  excluded.country_empty_last_scheduled_for, excluded.country_empty_first_received_at,
                  excluded.joined_date_set, excluded.joined_date, excluded.joined_date_effective_at)
