PermitUserEnvironment no

Match User hololive-pg-fence
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AuthorizedKeysFile /etc/ssh/authorized_keys/hololive-pg-fence
    ForceCommand /usr/local/libexec/hololive-postgres-failover/postgres-failover-ssh-dispatch.sh fence
    DisableForwarding yes
    PermitTTY no
    PermitUserRC no
    X11Forwarding no

Match User hololive-pg-route
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AuthorizedKeysFile /etc/ssh/authorized_keys/hololive-pg-route
    ForceCommand /usr/local/libexec/hololive-postgres-failover/postgres-failover-ssh-dispatch.sh route
    DisableForwarding yes
    PermitTTY no
    PermitUserRC no
    X11Forwarding no

Match all
