// Code generated by frontend/scripts/generate-api.mjs; DO NOT EDIT.
package contract

// Generation은 BFF와 브라우저가 공유하는 계약 내용의 SHA-256입니다.
const Generation = "c06bddfe3e2b69f6866e93426978bb55bfe3387510775be74e7e7394f251b118"

var operations = []Operation{
	{Method: "POST", Path: "/admin/api/auth/heartbeat", ID: "handle_heartbeat", Access: "session_csrf", Mutation: false},
	{Method: "POST", Path: "/admin/api/auth/login", ID: "handle_login", Access: "public_login", Mutation: false},
	{Method: "POST", Path: "/admin/api/auth/logout", ID: "handle_logout", Access: "session_csrf", Mutation: false},
	{Method: "GET", Path: "/admin/api/auth/session", ID: "handle_session_status", Access: "session", Mutation: false},
	{Method: "GET", Path: "/admin/api/docker/containers", ID: "handle_docker_containers", Access: "session", Mutation: false},
	{Method: "POST", Path: "/admin/api/docker/containers/{name}/restart", ID: "handle_docker_restart", Access: "session_csrf_audit", Mutation: true},
	{Method: "POST", Path: "/admin/api/docker/containers/{name}/start", ID: "handle_docker_start", Access: "session_csrf_audit", Mutation: true},
	{Method: "POST", Path: "/admin/api/docker/containers/{name}/stop", ID: "handle_docker_stop", Access: "session_csrf_audit", Mutation: true},
	{Method: "GET", Path: "/admin/api/docker/health", ID: "handle_docker_health", Access: "session", Mutation: false},
	{Method: "GET", Path: "/admin/api/holo/alarms", ID: "holoGetAlarms", Access: "session", Mutation: false},
	{Method: "DELETE", Path: "/admin/api/holo/alarms", ID: "holoDeleteAlarm", Access: "session_csrf_audit", Mutation: true},
	{Method: "GET", Path: "/admin/api/holo/members", ID: "holoGetMembers", Access: "session", Mutation: false},
	{Method: "POST", Path: "/admin/api/holo/members", ID: "holoAddMember", Access: "session_csrf_audit", Mutation: true},
	{Method: "GET", Path: "/admin/api/holo/members/calendar", ID: "holoGetCalendar", Access: "session", Mutation: false},
	{Method: "POST", Path: "/admin/api/holo/members/{id}/aliases", ID: "holoAddAlias", Access: "session_csrf_audit", Mutation: true},
	{Method: "DELETE", Path: "/admin/api/holo/members/{id}/aliases", ID: "holoRemoveAlias", Access: "session_csrf_audit", Mutation: true},
	{Method: "PATCH", Path: "/admin/api/holo/members/{id}/channel", ID: "holoUpdateChannel", Access: "session_csrf_audit", Mutation: true},
	{Method: "PATCH", Path: "/admin/api/holo/members/{id}/graduation", ID: "holoSetGraduation", Access: "session_csrf_audit", Mutation: true},
	{Method: "PATCH", Path: "/admin/api/holo/members/{id}/name", ID: "holoUpdateMemberName", Access: "session_csrf_audit", Mutation: true},
	{Method: "POST", Path: "/admin/api/holo/names/room", ID: "holoSetRoomName", Access: "session_csrf_audit", Mutation: true},
	{Method: "POST", Path: "/admin/api/holo/names/user", ID: "holoSetUserName", Access: "session_csrf_audit", Mutation: true},
	{Method: "GET", Path: "/admin/api/holo/rooms", ID: "holoGetRooms", Access: "session", Mutation: false},
	{Method: "POST", Path: "/admin/api/holo/rooms", ID: "holoAddRoom", Access: "session_csrf_audit", Mutation: true},
	{Method: "DELETE", Path: "/admin/api/holo/rooms", ID: "holoRemoveRoom", Access: "session_csrf_audit", Mutation: true},
	{Method: "GET", Path: "/admin/api/holo/rooms/joined", ID: "holoGetRoomsJoined", Access: "session", Mutation: false},
	{Method: "POST", Path: "/admin/api/holo/rooms/acl", ID: "holoSetAcl", Access: "session_csrf_audit", Mutation: true},
	{Method: "GET", Path: "/admin/api/holo/settings", ID: "holoGetSettings", Access: "session", Mutation: false},
	{Method: "POST", Path: "/admin/api/holo/settings", ID: "holoUpdateSettings", Access: "session_csrf_audit", Mutation: true},
	{Method: "GET", Path: "/admin/api/holo/stats", ID: "holoGetStats", Access: "session", Mutation: false},
	{Method: "GET", Path: "/admin/api/holo/stats/youtube/community-shorts", ID: "holoGetYouTubeCommunityShortsOps", Access: "session", Mutation: false},
	{Method: "GET", Path: "/admin/api/holo/streams/live", ID: "holoGetLiveStreams", Access: "session", Mutation: false},
	{Method: "GET", Path: "/admin/api/holo/streams/upcoming", ID: "holoGetUpcomingStreams", Access: "session", Mutation: false},
	{Method: "GET", Path: "/admin/api/status", ID: "handle_aggregated_status", Access: "session", Mutation: false},
	{Method: "GET", Path: "/admin/meta.json", ID: "getAdminMetadata", Access: "public_metadata", Mutation: false},
	{Method: "GET", Path: "/admin/api/openapi.json", ID: "getAdminOpenAPI", Access: "session", Mutation: false},
}
