package communityshortsops

import (
	"github.com/kapu/hololive-youtube-producer/internal/ops/communityshorts/internal/reports/channelsummary"
	"github.com/kapu/hololive-youtube-producer/internal/ops/communityshorts/internal/reports/deliverylogs"
	"github.com/kapu/hololive-youtube-producer/internal/ops/communityshorts/internal/reports/latencycause"
	"github.com/kapu/hololive-youtube-producer/internal/ops/communityshorts/internal/reports/routereport"
	"github.com/kapu/hololive-youtube-producer/internal/ops/communityshorts/internal/reports/sendcounts"
)

type CommunityShortsChannelSummaryReport = channelsummary.Report
type CommunityShortsChannelSummaryTotals = channelsummary.Totals
type CommunityShortsDeliveryLogQueryMode = deliverylogs.QueryMode
type CommunityShortsDeliveryLogCollectOptions = deliverylogs.CollectOptions
type CommunityShortsDeliveryLogReport = deliverylogs.Report
type CommunityShortsDeliveryLogQuery = deliverylogs.Query
type CommunityShortsDeliveryLogSummary = deliverylogs.Summary
type CommunityShortsDeliveryLogRow = deliverylogs.Row
type CommunityShortsLatencyCauseQueryMode = latencycause.QueryMode
type CommunityShortsInternalCauseJudgment = latencycause.InternalCauseJudgment
type CommunityShortsLatencyCauseCollectOptions = latencycause.CollectOptions
type CommunityShortsLatencyCauseQuery = latencycause.Query
type CommunityShortsLatencyCauseVerification = latencycause.Verification
type CommunityShortsLatencyCauseEvidence = latencycause.Evidence
type CommunityShortsLatencyCauseReport = latencycause.Report
type CommunityShortsLatencyCausePeriodView = latencycause.PeriodView
type CommunityShortsLatencyCauseSummary = latencycause.Summary
type CommunityShortsLatencyCauseRow = latencycause.Row
type CommunityShortsLatencyPeriodSpec = latencycause.PeriodSpec
type CommunityShortsLatencyPeriodReport = latencycause.PeriodReport
type CommunityShortsRouteVerificationReport = routereport.Report
type CommunityShortsRouteVerificationRuntime = routereport.Runtime
type CommunityShortsRouteVerificationSummary = routereport.Summary
type CommunityShortsRouteVerificationChannel = routereport.Channel
type CommunityShortsRouteVerificationRoute = routereport.Route
type CommunityShortsSendCountQueryMode = sendcounts.QueryMode
type CommunityShortsSendCountCollectOptions = sendcounts.CollectOptions
type CommunityShortsSendCountQuery = sendcounts.Query
type CommunityShortsSendCountReport = sendcounts.Report
type CommunityShortsSendCountSummary = sendcounts.Summary
type CommunityShortsSendCountVerificationStatus = sendcounts.VerificationStatus
type CommunityShortsSendCountVerification = sendcounts.Verification
type CommunityShortsSendCountRow = sendcounts.Row

const (
	CommunityShortsInternalCauseJudgmentInternalSystem = latencycause.InternalCauseJudgmentInternalSystem
	CommunityShortsInternalCauseJudgmentNonInternal    = latencycause.InternalCauseJudgmentNonInternal
)

var CollectCommunityShortsChannelSummaryReport = channelsummary.Collect
var BuildCommunityShortsChannelSummaryReport = channelsummary.Build
var RenderCommunityShortsChannelSummaryMarkdown = channelsummary.RenderMarkdown
var BuildCommunityShortsDeliveryLogReport = deliverylogs.Build
var RenderCommunityShortsDeliveryLogMarkdown = deliverylogs.RenderMarkdown
var CollectCommunityShortsDeliveryLogReport = deliverylogs.Collect
var BuildCommunityShortsLatencyCauseReport = latencycause.Build
var BuildCommunityShortsLatencyCauseReportWithQuery = latencycause.BuildWithQuery
var RenderCommunityShortsLatencyCauseMarkdown = latencycause.RenderMarkdown
var CollectCommunityShortsLatencyCauseReport = latencycause.Collect
var CollectCommunityShortsLatencyCauseReportWithOptions = latencycause.CollectWithOptions
var DefaultCommunityShortsLatencyPeriodSpecs = latencycause.DefaultPeriodSpecs
var CollectCommunityShortsLatencyPeriodReport = latencycause.CollectPeriodReport
var BuildCommunityShortsLatencyPeriodReport = latencycause.BuildPeriodReport
var RenderCommunityShortsLatencyPeriodMarkdown = latencycause.RenderPeriodMarkdown
var CollectCommunityShortsRouteVerificationReport = routereport.Collect
var BuildCommunityShortsRouteVerificationReport = routereport.Build
var RenderCommunityShortsRouteVerificationMarkdown = routereport.RenderMarkdown
var BuildCommunityShortsSendCountReport = sendcounts.Build
var BuildCommunityShortsSendCountReportWithQuery = sendcounts.BuildWithQuery
var RenderCommunityShortsSendCountMarkdown = sendcounts.RenderMarkdown
var CollectCommunityShortsSendCountReport = sendcounts.Collect
var CollectCommunityShortsSendCountReportWithOptions = sendcounts.CollectWithOptions
