apiVersion: v1
kind: Endpoints
metadata:
  name: holo-postgres
  namespace: hololive
$patch: delete
---
apiVersion: v1
kind: Endpoints
metadata:
  name: iris
  namespace: hololive
$patch: delete
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cliproxy
  namespace: hololive
$patch: delete
---
apiVersion: v1
kind: Endpoints
metadata:
  name: llm-server
  namespace: hololive
$patch: delete
---
apiVersion: v1
kind: Endpoints
metadata:
  name: game-bot-twentyq
  namespace: hololive
$patch: delete
---
apiVersion: v1
kind: Endpoints
metadata:
  name: game-bot-turtle
  namespace: hololive
$patch: delete
