package domain

import (
	model "github.com/kapu/hololive-shared/pkg/domain/internal/model"
	"github.com/kapu/hololive-shared/pkg/domain/internal/model/templatesampledata"
)

type AlarmType = model.AlarmType
type AlarmTypes = model.AlarmTypes
type Alarm = model.Alarm
type AlarmNotification = model.AlarmNotification
type AlarmQueueEnvelope = model.AlarmQueueEnvelope
type AlarmQueueRetryMetadata = model.AlarmQueueRetryMetadata
type AlarmDispatchSourceKind = model.AlarmDispatchSourceKind
type YouTubeOutboxDispatchPayload = model.YouTubeOutboxDispatchPayload
type CelebrationKind = model.CelebrationKind
type CelebrationDispatchPayload = model.CelebrationDispatchPayload
type CalendarEntry = model.CalendarEntry
type YouTubeOutboxItem = model.YouTubeOutboxItem
type Channel = model.Channel
type CommandType = model.CommandType
type ParseResult = model.ParseResult
type ParseResults = model.ParseResults
type CommandContext = model.CommandContext
type MemberIntentType = model.MemberIntentType
type MemberIntent = model.MemberIntent
type AddAlarmRequest = model.AddAlarmRequest
type AlarmEntry = model.AlarmEntry
type AlarmListView = model.AlarmListView
type AlarmRepository = model.AlarmRepository
type AlarmCache = model.AlarmCache
type AlarmStateManager = model.AlarmStateManager
type AlarmCRUD = model.AlarmCRUD
type AlarmDispatchState = model.AlarmDispatchState
type StreamProvider = model.StreamProvider
type MajorEventType = model.MajorEventType
type MajorEventLinkStatus = model.MajorEventLinkStatus
type MajorEvent = model.MajorEvent
type EventRoomSubscription = model.EventRoomSubscription
type Aliases = model.Aliases
type Member = model.Member
type MemberDataProvider = model.MemberDataProvider
type NextStreamStatus = model.NextStreamStatus
type NextStreamInfo = model.NextStreamInfo
type DeliveryOutboxKind = model.DeliveryOutboxKind
type DeliveryOutboxStatus = model.DeliveryOutboxStatus
type NotificationDeliveryOutbox = model.NotificationDeliveryOutbox
type TemplateKey = model.TemplateKey
type NotificationTemplate = model.NotificationTemplate
type NotificationTemplateRevision = model.NotificationTemplateRevision
type TalentProfile = model.TalentProfile
type TalentProfileEntry = model.TalentProfileEntry
type TalentSocialLink = model.TalentSocialLink
type Translated = model.Translated
type TranslatedProfileDataRow = model.TranslatedProfileDataRow
type StreamStatus = model.StreamStatus
type Stream = model.Stream
type OfficialTalent = model.OfficialTalent
type YouTubeChannelStatsSnapshot = model.YouTubeChannelStatsSnapshot
type YouTubeChannelProfile = model.YouTubeChannelProfile
type YouTubeVideo = model.YouTubeVideo
type YouTubeCommunityPost = model.YouTubeCommunityPost
type YouTubeContentAlarmTracking = model.YouTubeContentAlarmTracking
type YouTubeCommunityShortsSourcePost = model.YouTubeCommunityShortsSourcePost
type YouTubeCommunityShortsAlarmState = model.YouTubeCommunityShortsAlarmState
type YouTubeCommunityShortsObservationPostBaseline = model.YouTubeCommunityShortsObservationPostBaseline
type YouTubeCommunityShortsObservationWindow = model.YouTubeCommunityShortsObservationWindow
type WatermarkType = model.WatermarkType
type YouTubeContentWatermark = model.YouTubeContentWatermark
type OutboxKind = model.OutboxKind
type OutboxStatus = model.OutboxStatus
type YouTubeNotificationOutbox = model.YouTubeNotificationOutbox
type LiveStatus = model.LiveStatus
type YouTubeLiveSession = model.YouTubeLiveSession
type YouTubeLiveViewerSample = model.YouTubeLiveViewerSample
type YouTubeStreamStats = model.YouTubeStreamStats
type ThumbnailsJSON = model.ThumbnailsJSON
type ThumbnailEntry = model.ThumbnailEntry
type YouTubeNotificationDelivery = model.YouTubeNotificationDelivery
type YouTubeNotificationDeliveryTelemetry = model.YouTubeNotificationDeliveryTelemetry
type TimestampedStats = model.TimestampedStats
type MilestoneType = model.MilestoneType
type Milestone = model.Milestone
type StatsChange = model.StatsChange
type RankEntry = model.RankEntry

const (
	AlarmTypeLive                                  = model.AlarmTypeLive
	AlarmTypeCommunity                             = model.AlarmTypeCommunity
	AlarmTypeShorts                                = model.AlarmTypeShorts
	AlarmTypeBirthday                              = model.AlarmTypeBirthday
	AlarmTypeAnniversary                           = model.AlarmTypeAnniversary
	AlarmDispatchSourceKindYouTubeOutbox           = model.AlarmDispatchSourceKindYouTubeOutbox
	AlarmDispatchSourceKindCelebration             = model.AlarmDispatchSourceKindCelebration
	CelebrationKindBirthday                        = model.CelebrationKindBirthday
	CelebrationKindAnniversary                     = model.CelebrationKindAnniversary
	CommandLive                                    = model.CommandLive
	CommandUpcoming                                = model.CommandUpcoming
	CommandSchedule                                = model.CommandSchedule
	CommandHelp                                    = model.CommandHelp
	CommandAlarmAdd                                = model.CommandAlarmAdd
	CommandAlarmRemove                             = model.CommandAlarmRemove
	CommandAlarmList                               = model.CommandAlarmList
	CommandAlarmClear                              = model.CommandAlarmClear
	CommandAlarmInvalid                            = model.CommandAlarmInvalid
	CommandMemberInfo                              = model.CommandMemberInfo
	CommandStats                                   = model.CommandStats
	CommandSubscriber                              = model.CommandSubscriber
	CommandMemberNews                              = model.CommandMemberNews
	CommandMemberNewsSubscription                  = model.CommandMemberNewsSubscription
	CommandMajorEvent                              = model.CommandMajorEvent
	CommandCalendar                                = model.CommandCalendar
	CommandUnknown                                 = model.CommandUnknown
	MemberIntentUnknown                            = model.MemberIntentUnknown
	MemberIntentMemberInfo                         = model.MemberIntentMemberInfo
	MemberIntentOther                              = model.MemberIntentOther
	MajorEventStatusActive                         = model.MajorEventStatusActive
	MajorEventStatusEnded                          = model.MajorEventStatusEnded
	MajorEventStatusCanceled                       = model.MajorEventStatusCanceled
	MajorEventTypeEvent                            = model.MajorEventTypeEvent
	MajorEventTypeNews                             = model.MajorEventTypeNews
	MajorEventLinkStatusUnchecked                  = model.MajorEventLinkStatusUnchecked
	MajorEventLinkStatusOK                         = model.MajorEventLinkStatusOK
	MajorEventLinkStatusFailed                     = model.MajorEventLinkStatusFailed
	MajorEventLinkStatusBlocked                    = model.MajorEventLinkStatusBlocked
	NextStreamStatusLive                           = model.NextStreamStatusLive
	NextStreamStatusUpcoming                       = model.NextStreamStatusUpcoming
	NextStreamStatusNoUpcoming                     = model.NextStreamStatusNoUpcoming
	NextStreamStatusTimeUnknown                    = model.NextStreamStatusTimeUnknown
	DeliveryKindMajorEventWeekly                   = model.DeliveryKindMajorEventWeekly
	DeliveryKindMajorEventMonthly                  = model.DeliveryKindMajorEventMonthly
	DeliveryKindMemberNewsWeekly                   = model.DeliveryKindMemberNewsWeekly
	DeliveryKindMemberNewsMonthly                  = model.DeliveryKindMemberNewsMonthly
	DeliveryStatusPending                          = model.DeliveryStatusPending
	DeliveryStatusSent                             = model.DeliveryStatusSent
	DeliveryStatusFailed                           = model.DeliveryStatusFailed
	TemplateKeyOutboxShorts                        = model.TemplateKeyOutboxShorts
	TemplateKeyOutboxCommunity                     = model.TemplateKeyOutboxCommunity
	TemplateKeyOutboxVideo                         = model.TemplateKeyOutboxVideo
	TemplateKeyOutboxMilestone                     = model.TemplateKeyOutboxMilestone
	TemplateKeyOutboxVideoGroup                    = model.TemplateKeyOutboxVideoGroup
	TemplateKeyOutboxShortsGroup                   = model.TemplateKeyOutboxShortsGroup
	TemplateKeyOutboxCommunityGroup                = model.TemplateKeyOutboxCommunityGroup
	TemplateKeyCmdAlarmList                        = model.TemplateKeyCmdAlarmList
	TemplateKeyCmdAlarmNotification                = model.TemplateKeyCmdAlarmNotification
	TemplateKeyCmdAlarmLiveStarted                 = model.TemplateKeyCmdAlarmLiveStarted
	TemplateKeyCmdLiveStreams                      = model.TemplateKeyCmdLiveStreams
	TemplateKeyCmdUpcomingStreams                  = model.TemplateKeyCmdUpcomingStreams
	TemplateKeyCmdHelp                             = model.TemplateKeyCmdHelp
	TemplateKeyCmdMemberDirectory                  = model.TemplateKeyCmdMemberDirectory
	TemplateKeyCmdChannelSchedule                  = model.TemplateKeyCmdChannelSchedule
	TemplateKeyCmdAlarmAdded                       = model.TemplateKeyCmdAlarmAdded
	TemplateKeyCmdAlarmRemoved                     = model.TemplateKeyCmdAlarmRemoved
	TemplateKeyCmdAlarmCleared                     = model.TemplateKeyCmdAlarmCleared
	TemplateKeyCmdMilestoneAchieved                = model.TemplateKeyCmdMilestoneAchieved
	TemplateKeyCmdMilestoneApproach                = model.TemplateKeyCmdMilestoneApproach
	TemplateKeyCmdMajorEventWeeklySummary          = model.TemplateKeyCmdMajorEventWeeklySummary
	TemplateKeyCmdMajorEventMonthlySummary         = model.TemplateKeyCmdMajorEventMonthlySummary
	TemplateKeyCmdMajorEventSubscribed             = model.TemplateKeyCmdMajorEventSubscribed
	TemplateKeyCmdMajorEventUnsubscribed           = model.TemplateKeyCmdMajorEventUnsubscribed
	TemplateKeyCmdMajorEventAlreadySub             = model.TemplateKeyCmdMajorEventAlreadySub
	TemplateKeyCmdMajorEventNotSub                 = model.TemplateKeyCmdMajorEventNotSub
	TemplateKeyCmdMajorEventStatus                 = model.TemplateKeyCmdMajorEventStatus
	TemplateKeyCmdMajorEventUsage                  = model.TemplateKeyCmdMajorEventUsage
	TemplateKeyCmdMemberNewsDigest                 = model.TemplateKeyCmdMemberNewsDigest
	TemplateKeyCmdMemberNewsNoMembers              = model.TemplateKeyCmdMemberNewsNoMembers
	TemplateKeyCmdMemberNewsSubscribed             = model.TemplateKeyCmdMemberNewsSubscribed
	TemplateKeyCmdMemberNewsUnsubscribed           = model.TemplateKeyCmdMemberNewsUnsubscribed
	TemplateKeyCmdMemberNewsAlreadySub             = model.TemplateKeyCmdMemberNewsAlreadySub
	TemplateKeyCmdMemberNewsNotSub                 = model.TemplateKeyCmdMemberNewsNotSub
	TemplateKeyCmdMemberNewsStatus                 = model.TemplateKeyCmdMemberNewsStatus
	StreamStatusLive                               = model.StreamStatusLive
	StreamStatusUpcoming                           = model.StreamStatusUpcoming
	StreamStatusPast                               = model.StreamStatusPast
	YouTubeContentAlarmDeliveryStatusPending       = model.YouTubeContentAlarmDeliveryStatusPending
	YouTubeContentAlarmDeliveryStatusSent          = model.YouTubeContentAlarmDeliveryStatusSent
	YouTubeCommunityShortsAlarmStateStatusDetected = model.YouTubeCommunityShortsAlarmStateStatusDetected
	YouTubeCommunityShortsAlarmStateStatusEnqueued = model.YouTubeCommunityShortsAlarmStateStatusEnqueued
	YouTubeCommunityShortsAlarmStateStatusSent     = model.YouTubeCommunityShortsAlarmStateStatusSent
	WatermarkTypeVideo                             = model.WatermarkTypeVideo
	WatermarkTypeShort                             = model.WatermarkTypeShort
	WatermarkTypeCommunityPost                     = model.WatermarkTypeCommunityPost
	OutboxKindNewVideo                             = model.OutboxKindNewVideo
	OutboxKindNewShort                             = model.OutboxKindNewShort
	OutboxKindLiveStream                           = model.OutboxKindLiveStream
	OutboxKindCommunityPost                        = model.OutboxKindCommunityPost
	OutboxKindMilestone                            = model.OutboxKindMilestone
	OutboxStatusPending                            = model.OutboxStatusPending
	OutboxStatusSent                               = model.OutboxStatusSent
	OutboxStatusFailed                             = model.OutboxStatusFailed
	LiveStatusUpcoming                             = model.LiveStatusUpcoming
	LiveStatusLive                                 = model.LiveStatusLive
	LiveStatusEnded                                = model.LiveStatusEnded
	MilestoneSubscribers                           = model.MilestoneSubscribers
	MilestoneVideos                                = model.MilestoneVideos
	MilestoneViews                                 = model.MilestoneViews
)

var AllAlarmTypes = model.AllAlarmTypes
var DefaultAlarmTypes = model.DefaultAlarmTypes

var NewAlarmNotification = model.NewAlarmNotification
var NewCommandContext = model.NewCommandContext
var NormalizeMemberIntent = model.NormalizeMemberIntent
var LoadAllMembers = model.LoadAllMembers
var LoadProfiles = model.LoadProfiles
var NormalizeStatsPeriodToken = model.NormalizeStatsPeriodToken
var ResolveStatsPeriod = model.ResolveStatsPeriod
var LoadTalents = model.LoadTalents
var GetTemplateSampleData = templatesampledata.GetTemplateSampleData
var IsValidTemplateKey = templatesampledata.IsValidTemplateKey
var LoadTranslated = model.LoadTranslated
var ResolveYouTubeContentAlarmDeliveryStatus = model.ResolveYouTubeContentAlarmDeliveryStatus
var ResolveYouTubeCommunityShortsAlarmStateStatus = model.ResolveYouTubeCommunityShortsAlarmStateStatus
var BuildYouTubeNotificationDedupeKey = model.BuildYouTubeNotificationDedupeKey
