services:
  hololive-api:
    build:
      cache_from:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-api-buildcache:buildcache
      cache_to:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-api-buildcache:buildcache,mode=min,image-manifest=true,oci-mediatypes=true

  youtube-producer:
    build:
      cache_from:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-youtube-producer-buildcache:buildcache
      cache_to:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-youtube-producer-buildcache:buildcache,mode=min,image-manifest=true,oci-mediatypes=true
