services:
  hololive-bot:
    build:
      cache_from:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-kakao-bot-go-buildcache:buildcache
      cache_to:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-kakao-bot-go-buildcache:buildcache,mode=min,image-manifest=true,oci-mediatypes=true

  youtube-producer:
    build:
      cache_from:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-youtube-producer-buildcache:buildcache
      cache_to:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-youtube-producer-buildcache:buildcache,mode=min,image-manifest=true,oci-mediatypes=true

  llm-scheduler:
    build:
      cache_from:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-llm-scheduler-buildcache:buildcache
      cache_to:
        - type=registry,ref=${REMOTE_CACHE_PREFIX:?set REMOTE_CACHE_PREFIX}/hololive-llm-scheduler-buildcache:buildcache,mode=min,image-manifest=true,oci-mediatypes=true
