apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: hololive
spec:
  selector:
    app: admin-api
  type: NodePort
  ports:
    - name: http
      port: 30002
      targetPort: http
      nodePort: 30002
