apiVersion: v1
kind: Service
metadata:
  name: alarm-dispatcher
  namespace: hololive
spec:
  selector:
    app: alarm-dispatcher
  ports:
    - name: http
      port: 30010
      targetPort: http
  type: ClusterIP
