apiVersion: v1
kind: Service
metadata:
  name: hololive-bot
  namespace: hololive
spec:
  selector:
    app: hololive-bot
  type: NodePort
  ports:
    - name: http
      port: 30001
      targetPort: http
      nodePort: 30001
