apiVersion: v1
kind: Service
metadata:
  name: llm-scheduler
  namespace: hololive
spec:
  selector:
    app: llm-scheduler
  type: NodePort
  ports:
    - name: http
      port: 30003
      targetPort: http
      nodePort: 30003
