apiVersion: v1
kind: Service
metadata:
  name: stream-ingester
  namespace: hololive
spec:
  selector:
    app: stream-ingester
  type: NodePort
  ports:
    - name: http
      port: 30004
      targetPort: http
      nodePort: 30004
