ALTER TABLE members
    ADD COLUMN IF NOT EXISTS short_korean_name VARCHAR(64);

COMMENT ON COLUMN members.short_korean_name IS 'KakaoLink/list-card display nickname, distinct from search aliases.';

WITH short_names(slug, short_korean_name) AS (
  VALUES
    ('gawr-gura', '구라'),
    ('momosuzu-nene', '네네'),
    ('shirogane-noel', '노엘'),
    ('koganei-niko', '니코'),
    ('juufuutei-raden', '라덴'),
    ('yukihana-lamy', '라미'),
    ('himemori-luna', '루나'),
    ('takane-lui', '루이'),
    ('ayunda-risu', '리스'),
    ('houshou-marine', '마린'),
    ('gigi-murin', '지지'),
    ('ookami-mio', '미오'),
    ('sakuramiko', '미코'),
    ('hakos-baelz', '벨즈'),
    ('shishiro-botan', '보탄'),
    ('kikirara-vivi', '비비'),
    ('koseki-bijou', '비쥬'),
    ('tsukumo-sana', '사나'),
    ('tokino-sora', '소라'),
    ('mizumiya-su', '스우'),
    ('murasaki-shion', '시온'),
    ('hiodoshi-ao', '아오'),
    ('kureiji-ollie', '올리'),
    ('vestia-zeta', '제타'),
    ('yuzuki-choco', '초코'),
    ('kiryu-coco', '코코'),
    ('tokoyami-towa', '토와'),
    ('omaru-polka', '폴카'),
    ('shiori-novella', '노벨라'),
    ('pavolia-reine', '레이네'),
    ('aki-rosenthal', '로젠탈'),
    ('ichijou-ririka', '리리카'),
    ('isaki-riona', '리오나'),
    ('natsuiro-matsuri', '마츠리'),
    ('anya-melfissa', '멜피사'),
    ('mococo-abyssgard', '모코코'),
    ('nanashi-mumei', '무메이'),
    ('oozora-subaru', '스바루'),
    ('nakiri-ayame', '아야메'),
    ('azki', '아즈키'),
    ('minato-aqua', '아쿠아'),
    ('nekomata-okayu', '오카유'),
    ('tsunomaki-watame', '와타메'),
    ('kazama-iroha', '이로하'),
    ('rindo-chihaya', '치하야'),
    ('otonose-kanade', '카나데'),
    ('amane-kanata', '카나타'),
    ('inugami-korone', '코로네'),
    ('hakui-koyori', '코요리'),
    ('ouro-kronii', '크로니'),
    ('sakamata-chloe', '클로에'),
    ('takanashi-kiara', '키아라'),
    ('ceres-fauna', '파우나'),
    ('raora-panthera', '판테라'),
    ('usada-pekora', '페코라'),
    ('akai-haato', '하아토'),
    ('todoroki-hajime', '하지메'),
    ('shiranui-flare', '후레아'),
    ('shirakami-fubuki', '후부키'),
    ('fuwawa-abyssgard', '후와와'),
    ('la-darknesss', '다크니스'),
    ('roboco-san', '로보코상'),
    ('devis-regloss', '리글로스'),
    ('hoshimachi-suisei', '스이세이'),
    ('watson-amelia', '아멜리아'),
    ('irys', '아이리스'),
    ('ninomae-inanis', '이나니스'),
    ('cecilia-immergreen', '이머그린'),
    ('kobo-kanaeru', '카나에루'),
    ('mori-calliope', '칼리오페'),
    ('holoan-room', '호로아나'),
    ('moona-hoshinova', '호시노바'),
    ('airani-iofifteen', '이오피프틴'),
    ('kaela-kovalskia', '코발스키아'),
    ('hololive-official', '홀로라이브'),
    ('elizabeth-rose-bloodflame', '블러드플레임'),
    ('devis-flowglow', '플로우글로우'),
    ('nerissa-ravencroft', '레이븐크로프트'),
    ('hololive-en-official', '홀로EN'),
    ('hololive-id-official', '홀로ID'),
    ('sameko-saba', '사바'),
    ('yuuki-sakuna', '사쿠나'),
    ('aokumo-rin', '린'),
    ('hanako-nana', '나나'),
    ('akane-lize', '리제'),
    ('yuzuha-riko', '리코'),
    ('ayatsuno-yuni', '유니'),
    ('airi-kanna', '칸나'),
    ('arahashi-tabi', '타비'),
    ('sakihane-fuya', '후야'),
    ('shirayuki-hina', '히나'),
    ('neneko-mashiro', '마시로'),
    ('tenko-shibuki', '시부키'),
    ('hanabusa-lisa', '리사'),
    ('tosaki-mimi', '미미'),
    ('asumi-sena', '세나'),
    ('amayui-moka', '모카'),
    ('choya-hanabi', '하나비'),
    ('narin-mikure', '나린'),
    ('jira-jisaki', '지라'),
    ('remia-aotsuki', '레미아'),
    ('riko-solari', '솔라리'),
    ('arya-kuroha', '아리야'),
    ('eris-suzukami', '에리스'),
    ('sendo-yuuhi', '유우히'),
    ('tsumugi-kokage', '코카게'),
    ('yano-kuromu', '쿠로무'),
    ('kisaragi-ren', '렌'),
    ('kurumi-noah', '노아'),
    ('tachibana-hinano', '히나노'),
    ('kogara-toto', '토토'),
    ('kaga-nazuna', '나즈나'),
    ('kaga-sumire', '스미레'),
    ('ichinose-uruha', '우루하'),
    ('komori-met', '메토'),
    ('yakumo-beni', '베니'),
    ('aizawa-ema', '에마'),
    ('nekota-tsuna', '츠나'),
    ('tatsumaki-chise', '치세'),
    ('kaminari-qpi', '큐피'),
    ('shiranami-ramune', '라무네'),
    ('ginjo-saine', '사이네'),
    ('yumeno-akari', '아카리'),
    ('shinomiya-runa', '시노미야')
)
UPDATE members AS m
SET short_korean_name = s.short_korean_name
FROM short_names AS s
WHERE m.slug = s.slug
  AND m.short_korean_name IS DISTINCT FROM s.short_korean_name;
