-- 구 payload 열만 준비 단계의 정본입니다. 사전은 그 값에서 파생하며 241에서 구 열을 제거합니다.
-- 현재 manifest 전환은 writer 정지 뒤 독립 commit의 최대 1000행 backfill을 사용합니다.
SET lock_timeout = '3s';
CREATE TABLE IF NOT EXISTS public.source_observation_payloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_kind TEXT NOT NULL,
    schema_version SMALLINT NOT NULL CHECK (schema_version > 0),
    canonical_profile TEXT NOT NULL CHECK (canonical_profile = 'source-observation-canonical-json-v1'),
    payload_sha256 BYTEA NOT NULL CHECK (octet_length(payload_sha256) = 32),
    payload JSONB NOT NULL CHECK (
        jsonb_typeof(payload) = 'object' AND octet_length(payload::text) <= 1048576
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_source_observation_payload_digest UNIQUE (
        observation_kind, schema_version, canonical_profile, payload_sha256
    )
);
ALTER TABLE public.source_observation_payloads ALTER COLUMN payload SET STORAGE EXTENDED;
ALTER TABLE public.source_observation_payloads ALTER COLUMN payload SET COMPRESSION lz4;
ALTER TABLE public.source_observations ADD COLUMN IF NOT EXISTS payload_id BIGINT;
RESET lock_timeout;

CREATE OR REPLACE FUNCTION public.backfill_source_observation_payloads(requested_limit integer)
RETURNS integer
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
DECLARE
    ids bigint[];
    migrated integer;
    selected integer;
BEGIN
    IF requested_limit IS NULL OR requested_limit NOT BETWEEN 1 AND 1000 THEN
        RAISE EXCEPTION 'payload backfill limit must be 1..1000';
    END IF;

    -- Header locks survive all statements in this function. No persisted cursor:
    -- committed deletes/late inserts cannot be skipped on restart.
    SELECT array_agg(batch.id)
    INTO ids
    FROM (
        SELECT id
        FROM public.source_observations
        WHERE payload_id IS NULL
        ORDER BY id
        LIMIT requested_limit
        FOR UPDATE SKIP LOCKED
    ) AS batch;
    selected := coalesce(array_length(ids, 1), 0);
    IF selected = 0 THEN
        RETURN 0;
    END IF;

    INSERT INTO public.source_observation_payloads (
        observation_kind, schema_version, canonical_profile, payload_sha256, payload
    )
    SELECT keys.observation_kind, keys.schema_version,
           'source-observation-canonical-json-v1', decode(keys.payload_sha256, 'hex'),
           keys.payload
    FROM (
        SELECT DISTINCT ON (observation_kind, schema_version, payload_sha256)
               observation_kind, schema_version, payload_sha256, payload
        FROM public.source_observations
        WHERE id = ANY(ids)
        ORDER BY observation_kind, schema_version, payload_sha256, id
    ) AS keys
    ORDER BY keys.observation_kind, keys.schema_version, keys.payload_sha256
    ON CONFLICT (observation_kind, schema_version, canonical_profile, payload_sha256) DO NOTHING;

    -- A separate statement sees rows inserted by competing committed batches
    -- even when ON CONFLICT waited on a row invisible to the insert snapshot.
    WITH updated AS (
        UPDATE public.source_observations AS observation
        SET payload_id = dictionary.id
        FROM public.source_observation_payloads AS dictionary
        WHERE observation.id = ANY(ids)
          AND dictionary.observation_kind = observation.observation_kind
          AND dictionary.schema_version = observation.schema_version
          AND dictionary.canonical_profile = 'source-observation-canonical-json-v1'
          AND dictionary.payload_sha256 = decode(observation.payload_sha256, 'hex')
          AND dictionary.payload = observation.payload
        RETURNING observation.id
    )
    SELECT count(updated.id) INTO migrated FROM updated;

    IF selected <> migrated THEN
        RAISE EXCEPTION 'payload backfill digest collision, content mismatch, or missing dictionary row (% of %)', migrated, selected;
    END IF;
    RETURN migrated;
END
$function$;
REVOKE ALL ON FUNCTION public.backfill_source_observation_payloads(integer) FROM PUBLIC;
