#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <rollback-artifact.sql>" >&2
  exit 2
fi
root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${root}/libpq-connection.sh"
require_libpq_service
artifact="$1"
tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

mapfile -t indexes < <(sed -n 's/^DROP INDEX IF EXISTS \([^;]*\);/\1/p' "${root}/114_drop_unused_indexes.sql")
(( ${#indexes[@]} > 0 )) || { echo "migration 114 index inventory is empty" >&2; exit 1; }

array="$(printf "'%s'," "${indexes[@]}")"
array="${array%,}"
psql -w -X -v ON_ERROR_STOP=1 -At <<SQL >"${tmp}"
WITH expected(name) AS (SELECT unnest(ARRAY[${array}]::text[])),
defs AS (
  SELECT e.name, pg_get_indexdef(c.oid) AS definition
  FROM expected e
  LEFT JOIN pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
    ON c.relkind = 'i' AND c.relname = e.name
)
SELECT 'MISSING ' || name FROM defs WHERE definition IS NULL
UNION ALL
SELECT regexp_replace(
  definition,
  '^CREATE (UNIQUE )?INDEX ',
  'CREATE \1INDEX IF NOT EXISTS '
) || ';' FROM defs WHERE definition IS NOT NULL
ORDER BY 1;

SELECT CASE WHEN c.oid IS NULL THEN 'MISSING members_slug_key'
  ELSE 'DO \$restore\$ BEGIN IF NOT EXISTS (' ||
    'SELECT 1 FROM pg_constraint WHERE conname = ''members_slug_key'' ' ||
    'AND conrelid = ''public.members''::regclass' ||
    ') THEN ALTER TABLE public.members ADD CONSTRAINT members_slug_key ' ||
    pg_get_constraintdef(c.oid) || '; END IF; END \$restore\$;'
END
FROM (SELECT 1) seed
LEFT JOIN pg_constraint c ON c.conname = 'members_slug_key' AND c.conrelid = 'public.members'::regclass;
SQL

if grep -q '^MISSING ' "${tmp}"; then
  grep '^MISSING ' "${tmp}" >&2
  echo "migration 114 restore preflight failed; no index or constraint may be dropped without a captured definition" >&2
  exit 1
fi

{
  echo '-- Generated by preflight-114-restore.sh before applying 114_drop_unused_indexes.sql.'
  echo '-- Apply only after explicit rollback approval and quiescing all database writers.'
  echo '\set ON_ERROR_STOP on'
  echo "SET lock_timeout = '5s';"
  echo "SET statement_timeout = '15min';"
  echo 'SET search_path = public, pg_catalog;'
  echo 'BEGIN;'
  cat "${tmp}"
  echo 'COMMIT;'
} >"${artifact}"

echo "migration 114 rollback artifact captured: ${artifact} (${#indexes[@]} indexes plus members_slug_key)"
