package logschema

const (
	CommunityPostDetectedMessage          = "YouTube community post detected"
	ShortDetectedMessage                  = "YouTube short detected"
	CommunityShortsDetectionBatchMessage  = "YouTube community/shorts detection batch"
	CommunityShortsDeliveryAttemptMessage = "YouTube community/shorts delivery attempt started"
	CommunityShortsDeliveryResultMessage  = "YouTube community/shorts delivery result"
	CommunityShortsDeliveryAuditMessage   = "YouTube community/shorts delivery audit"
	FieldDeliveryID                       = "delivery_id"
	FieldOutboxID                         = "outbox_id"
	FieldRoomID                           = "room_id"
	FieldChannelID                        = "channel_id"
	FieldPostID                           = "post_id"
	FieldContentID                        = "content_id"
	FieldAlarmType                        = "alarm_type"
	FieldActualPublishedAt                = "actual_published_at"
	FieldAlarmSentAt                      = "alarm_sent_at"
	FieldAlarmLatencyMillis               = "alarm_latency_millis"
	FieldAlarmLatencyExceeded             = "alarm_latency_exceeded"
	FieldDetectedAt                       = "detected_at"
	FieldDetectedCount                    = "detected_count"
	FieldObservationStatus                = "observation_status"
	FieldObservationRuntimeName           = "observation_runtime_name"
	FieldObservationBigBangCutoverAt      = "observation_bigbang_cutover_at"
	FieldObservationStartedAt             = "observation_started_at"
	FieldObservationEndedAt               = "observation_ended_at"
	FieldSentAt                           = "sent_at"
	FieldSendResult                       = "send_result"
	FieldFailureReason                    = "failure_reason"
	FieldDeliveryMode                     = "delivery_mode"
	FieldDeliveryPath                     = "delivery_path"
	FieldDedupeKey                        = "dedupe_key"
	FieldAttemptOrdinal                   = "attempt_ordinal"
	FieldAttemptStartedAt                 = "attempt_started_at"
	FieldLatencyClassification            = "latency_classification"
	FieldTelemetrySource                  = "telemetry_source"
	FieldTargetAlarmCount                 = "target_alarm_count"
	FieldSuccessfulAlarmCount             = "successful_alarm_count"
	FieldFailedAlarmCount                 = "failed_alarm_count"
	FieldTargetRoomCount                  = "target_room_count"
	FieldSuccessfulRoomCount              = "successful_room_count"
	FieldFailedRoomCount                  = "failed_room_count"
	TelemetrySourcePersistentBuffer       = "persistent_buffer"
	TelemetrySourceOutboxFinalResult      = "outbox_final_result"
	DeliveryModeFinalResult               = "final_result"
)
